version: '3.7'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    build: .
    ports:
      - '3000:3000'
    networks:
      - home_development
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-data:/data/db
    networks:
      - home_development
    ports:
      - '27017:27017'
volumes:
  db-data:

networks:
  home_development:
